### your site title here

title: Manideep Mamindlapally
description: Student | IIT Kharagpur | 人の夢は　終わらねェ！

baseurl: / #name of GitHub repository
url: "" #custom url to be used instead of GitHub repository

disqus-shortname: manideepmamindlapally

highlighter: rouge
markdown: kramdown

# Pagination
paginate: 5
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
facebook: "manideepyx"
twitter: "manideepyx"
linkedin: "manideep-mamindlapally"
github: "manideepmamindlapally"
researchgate: "Manideep-Mamindlapally"
orcid: "0000-0002-8157-3972"
googlescholar: "w-PmSxAAAAAJ"
ieee: "37088954248"
email: "manideepyx@iitkgp.ac.in"
analytics: "G-70TMRMK71X"

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
